name: Idea
description: Suggest a feature or an improvement
labels: [idea]
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do?
      description: The situation or problem, rather than a specific solution.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would help?
